#!/bin/bash

restore() {
    function conf() {
        IFS=':' read -r -a array <<< "$1"
        # shellcheck disable=SC2046
        # shellcheck disable=SC2005
        echo $(sudo sed -nr "/^\[${array[0]}\]/ { :l /^${array[1]}[ ]*=/ { s/.*=[ ]*//; p; q;}; n; b l;}" /etc/mysql/debian.cnf)
    }
    MYSQL_USER=$(conf client:user)
    MYSQL_PASSWORD=$(conf client:password)
    ADD_CODE="############### tritium add ###############"

    if [[ ! $(cat ~/.bashrc) =~ $ADD_CODE ]]
    then
echo "
$ADD_CODE
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/[\1]/'
}
export PS1=\"\${debian_chroot:+(\$debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\[\033[32m\]\$(parse_git_branch)\[\033[00m\]\$ \"
alias mysql@self='mycli -u$MYSQL_USER -p$MYSQL_PASSWORD'
" >> ~/.bashrc
    fi

    if [[ ! $(cat ~/.profile) =~ $ADD_CODE ]]
    then
echo "
$ADD_CODE
export GOROOT=/usr/lib/go
export GOPATH=~/Golang
export PATH=\$PATH:~/Golang/bin
" >> ~/.profile
    fi

    # install docker
    DOCKER_SOURCE="https://mirrors.ustc.edu.cn/docker-ce/linux/ubuntu"

    if [[ ! $(cat /etc/apt/sources.list) =~ $DOCKER_SOURCE ]]
    then
        sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] $DOCKER_SOURCE $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io
    fi
}

backup() {
    # control
    mkdir -p .dist/DEBIAN
echo "\
package: tritium
version: 0.0.1
architecture: amd64
maintainer: cisordeng
description: Restore and Backup.
" > .dist/DEBIAN/control

    # control
    mkdir -p .dist/DEBIAN
echo "\
package: tritium
version: 0.0.1
architecture: amd64
maintainer: cisordeng
description: Restore and Backup.
depends: vim, nginx, mysql-client, mycli, golang, nodejs
" > .dist/DEBIAN/control

    # link
    BASH_PATH=$(readlink -f "$0")
    mkdir -p  ".dist/usr/bin"
    cp "$BASH_PATH" ".dist/usr/bin/${NAME}"

    # add backup files
    BACKUP_FILES=$(cat ~/.tritiumfiles)
    for file in $BACKUP_FILES
    do
        if [ ! -d "$file" ] && [ ! -f "$file" ]
        then
            echo "[$file] not directory or file!"
            continue
        fi
        echo "add $file"
        cp -r --parents "$file" .dist
    done

    dpkg -b .dist "tritium_$(date "+%Y%m%d%H%M%S").deb"
    rm -rf .dist
}

add() {
    if [ ! -d "$1" ] && [ ! -f "$1" ]
    then
        echo "[$1] not directory or file!"
        return
    fi

    BACKUP_FILES=$(cat ~/.tritiumfiles)
    if [[ $BACKUP_FILES =~ $1 ]]
    then
        echo "[$1] is exist!"
        return
    fi

    echo "$1" >> ~/.tritiumfiles
}

if [ "$1" == "restore" ]
then
    restore
elif [ "$1" == "backup" ]
then
    backup
elif [ "$1" == "add" ]
then
    add "$2"
else
  echo "missing parameter!"
fi
