#!/bin/bash
function conf() {
    IFS=':' read -r -a array <<< "$1"
    # shellcheck disable=SC2046
    # shellcheck disable=SC2005
    echo $(sudo sed -nr "/^\[${array[0]}\]/ { :l /^${array[1]}[ ]*=/ { s/.*=[ ]*//; p; q;}; n; b l;}" /etc/mysql/debian.cnf)
}
MYSQL_USER=$(conf client:user)
MYSQL_PASSWORD=$(conf client:password)
USER=$(eval getent passwd {$(awk '/^UID_MIN/ {print $2}' /etc/login.defs)..$(awk '/^UID_MAX/ {print $2}' /etc/login.defs)} | cut -d: -f1)
if [ -d /.tritiumhomefiles ]
then
    sudo cp -r /.tritiumhomefiles/* ~/
    for file in $(ls -a /.tritiumhomefiles)
    do
        if [ "$file" == "." ] || [ "$file" == ".." ]
        then
            continue
        fi
        chown -R $USER:$USER ~/$file
    done
    sudo rm -rf /.tritiumhomefiles
fi

sudo mysqldump -u${MYSQL_USER} -p${MYSQL_PASSWORD} --all-databases < /.mysql.sql

